#!/usr/bin/env bash
if [ -z $PACKAGE ]
then
    echo "Please set \$PACKAGE"
    exit 1
fi
AUR_USER=aurbuilder
sudo -u $AUR_USER -D~ bash -c "yay -S --needed --noprogressbar --needed --noconfirm $PACKAGE"
find /var/$AUR_USER -iname *pkg.tar* -exec tar --transform 's/.*\///g'  -rvf /tmp/all-packages.tar "{}" \;
